// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © rinebob

//@version=5
indicator("rb Utilities", "rb Utils", true, timeframe="", timeframe_gaps=false)
formattedTime = str.format_time(time, "yyyy-MM-dd HH:mm", syminfo.timezone)


log.info('============ START {0} {1} ============================', formattedTime, bar_index)
log.info('bar index: {0} ', bar_index)
log.info('ticker: {0} ', syminfo.ticker)
log.info('last bar time: {0} ', last_bar_time)
log.info('real time bar: {0} ', barstate.isrealtime)
log.info('high: {0} ', high)

/////////////// OHLC DATA /////////////////////////////
// Plot previous day high/low
[po, ph, pl, pc] = request.security(syminfo.tickerid, "D", [open[1], high[1], low[1], close[1]])
[o, h, l, c] = request.security(syminfo.tickerid, "D", [open, high, low, close])

///////////// PREVIOUS DAY HIGH / LOW ////////////////////////////
// log.info('ohlc: {0} {1} {2} {3} ', o, h, l, c)
// log.info('prev ohlc: {0} {1} {2} {3} ', po, ph, pl, pc)
highToPlot = barstate.ishistory ? h : ph
lowToPlot = barstate.ishistory ? l : pl

plot(highToPlot, "high", color = color.yellow )
plot(lowToPlot, "low", color = color.lime)

///////////// END PREVIOUS DAY HIGH / LOW ////////////////////////////

log.info('============= END {0} =============================', formattedTime)


// Utility scripts to plot various helper visuals:
// Bar number
// New day (=session break)
// New hour
// Previous day high/low
// Opening range high/low
// ZigZag with elapsed time and number of bars
// 



// plot(bar_index, "bar index")
